### ISSUE TITLE
Commits

### ISSUE THREAD

**Issue by mactzu** [mech-development/mdbc#1]
This is a cool idea.  i need ability to upload and commit

**Comment by mech-mechanic** [comment]
# Yo

I'm made you an **admin** for the [repo](https://github.com/mech-development/mdbc) so you should be good to commit and also add other collaborators if you think anyone else might want to join in!

**Comment by mactzu** [comment]
Sick bro

On 27 Aug. 2017 8:49 am, "Mike V" <notifications@github.com> wrote:

#Yo

I'm made you an *admin* for the repo so you should be good to commit and
also add other collaborators if you think anyone else might want to join in!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mech-development/mdbc/issues/1#issuecomment-325166118>,
or mute the thread
